name: Release ZIP file packaging

on:
  release:
    types: [published]

jobs:
  create_zip:
    runs-on: ubuntu-latest
    env:
      URL: https://windmill.service.avaloq.com/api/w/cloud-and-infra-lab/jobs/run/p/f/alpha/create_oci_stack_from_github_terraform_published_by_csa
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v2
      - name: 'Make (and upload) ZIP file(s)'
        uses: oracle-devrel/action-release-zip-maker@v0.5
        id: zip_maker
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
      - name: 'Call Private Template on OCI through Windmill'   
        run: | 
          GIT_HUB_REPO_PATH=$GITHUB_SERVER_URL
          GIT_HUB_REPO_NAME=$GITHUB_REPOSITORY
          GIT_HUB_EVENT_RELAEASE_TAG_NAME=${{ github.event.release.tag_name }}

          REPO_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY

          echo "Calling GIT_HUB_REPO_PATH $GIT_HUB_REPO_PATH  GIT_HUB_REPO_NAME $GIT_HUB_REPO_NAME GIT_HUB_EVENT_RELAEASE_TAG_NAME $GIT_HUB_EVENT_RELAEASE_TAG_NAME"
          
          # Get the repository description
          REPO_DESCRIPTION=$(curl -s -H "Authorization: token ${{ secrets.GIT_TOKEN }}" "https://api.github.com/repos/$GITHUB_REPOSITORY")
          # Extract the description field from the JSON response
          DESCRIPTION=$(echo "$REPO_DESCRIPTION" | jq -r '.description')


          # Get the Releasae Path
          RELEASE_DESCRIPTION=$(curl -s -H "Authorization: token ${{ secrets.GIT_TOKEN }}" "https://api.github.com/repos/$GITHUB_REPOSITORY/releases/tags/$GIT_HUB_EVENT_RELAEASE_TAG_NAME")
          # Extract the browser_download_url field from the JSON response
          BROWSER_DOWNLOAD_URL=$(echo "$RELEASE_DESCRIPTION" | jq -r '.browser_download_url')
          echo "BROWSER_DOWNLOAD_URL $BROWSER_DOWNLOAD_URL"


          # BODY='{"stack_description":"WINDMILL-OCI-STACK-FROM-GITHUB-RESOURCE-MANAGER","stack_name":"WINDMILL-OCI-STACK-FROM-GITHUB-RESOURCE-MANAGER","branch_name":"'$BRANCH_NAME'","repository_url":"'$REPO_URL'"}'
          # echo "Calling the API for $REPO_URL for branch $BRANCH_NAME with BODY $BODY"
          # UUID=$(curl -s -H 'Content-Type: application/json' -H "Authorization: Bearer $CSA_GIT_HUB_WINDMILL" -H "CF-Access-Client-Id: $CF_ACCESS_CLIENT_ID" -H "CF-Access-Client-Secret: $CF_ACCESS_CLIENT_SECRET"  -X POST -d $BODY $URL)
          # CHECK_URL="https://windmill.service.avaloq.com/api/w/cloud-and-infra-lab/jobs_u/completed/get_result_maybe/$UUID"
          # while true; do  
          #   RESPONSE=$(curl -s -H "Authorization: Bearer $CSA_GIT_HUB_WINDMILL" -H "CF-Access-Client-Id: $CF_ACCESS_CLIENT_ID" -H "CF-Access-Client-Secret: $CF_ACCESS_CLIENT_SECRET" $CHECK_URL)
          #   COMPLETED=$(echo $RESPONSE | jq .completed)
          #   if [ "$COMPLETED" = "true" ]; then
          #     echo $RESPONSE | jq .result
          #     break
          #   else
          #     sleep 1
          #   fi    
          # done 



