name: Release ZIP file packaging

on:
  release:
    types: [published]

jobs:
  create_zip:
    runs-on: ubuntu-latest
    env:
      URL: https://windmill.service.avaloq.com/api/w/cloud-and-infra-lab/jobs/run/p/f/alpha/create_oci_stack_from_github_terraform_published_by_csa
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v2
      - name: 'Make (and upload) ZIP file(s)'
        uses: oracle-devrel/action-release-zip-maker@v0.5
        id: zip_maker
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
      - name: 'Call Private Template on OCI through Windmill'   
        run: | 
          GIT_HUB_REPO_PATH=$GITHUB_SERVER_URL
          GIT_HUB_REPO_NAME=$GITHUB_REPOSITORY
          GIT_HUB_EVENT_RELAEASE_TAG_NAME=${{ github.event.release.tag_name }}
          U_GIT_HUB_REPO = ${{ github.repository }}


          REPO_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY
          echo "Calling U_GIT_HUB_REPO $U_GIT_HUB_REPO GIT_HUB_REPO_PATH $GIT_HUB_REPO_PATH  GIT_HUB_REPO_NAME $GIT_HUB_REPO_NAME GIT_HUB_EVENT_RELAEASE_TAG_NAME $GIT_HUB_EVENT_RELAEASE_TAG_NAME"
          
          # Get the repository description
          REPO_DESCRIPTION=$(curl -s -H "Authorization: token ${{ secrets.GIT_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/repository")

          # Extract the description field from the JSON response
          DESCRIPTION=$(echo "$REPO_DESCRIPTION" | jq -r '.description')
          echo "DESCRIPTION $DESCRIPTION"

